controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    publish_rate: 50.0

    # Các joint tên phải trùng trong URDF
    left_wheel_names: ['base_left_wheel_joint']
    right_wheel_names: ['base_right_wheel_joint']

    # wheels_per_side: 2
    wheel_separation: 0.21
    wheel_radius: 0.05

    base_frame_id: base_footprint
    odom_frame_id: odom
    use_stamped_vel: false  # This will make it use geometry_msgs/msg/Twist
    # cmd_vel_topic: /cmd_vel  # Changed to cmd_vel_topic and added leading slash
    # publish_cmd: true
    enable_odom_tf: true


    # (Tuỳ chọn)
    linear.x.has_velocity_limits: false
    angular.z.has_velocity_limits: false
